# Generated by Django 4.0.6 on 2022-07-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(choices=[('sahel', 'sahel'), ('yekan', 'yekan')], max_length=10, verbose_name='انتخاب فونت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'فونت',
                'verbose_name_plural': 'فونت ها',
            },
        ),
    ]
