# Generated by Django 4.0.6 on 2022-07-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_persian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='font',
            field=models.CharField(choices=[('sahel', 'sahel'), ('yekan', 'yekan')], default='sahel', max_length=10, verbose_name='انتخاب فونت'),
        ),
    ]
