# Generated by Django 4.0.6 on 2022-07-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_persian', '0002_alter_font_font'),
    ]

    operations = [
        migrations.RenameField(
            model_name='font',
            old_name='font',
            new_name='name',
        ),
    ]
